# Python Review Crash Course - Part II

## Data Structures (Lists and other Sequences), Numpy Arrays, Functions, PEPs

Developed by Shing Chi Leung in Jan 2023 &#128512;	

Based on the course structure developed by Andrea Dziubek

## List object, operation and iterable

In Lecture 1 we have touched on the concept of a list, which is an object. This is an important and flexible data structure which has extremely wide use. There are other important data structures we will not have time to explore the fundamental use of, for example `dict`, `tuple`, and `set`. These will be useful for data science use or development of software beyond mathematics. 

In Python when we construct a list, we are creating a list *object* to work on. To declare a list object, we type
```
# it generates an empty list
a = [] 

# it generates a list with 4 elements
b = [1, 2.1, 'a', True] 
```

It suffices to observe two features in a Python list. (Notice: the exact properties of a (linked) list depends on the language. For example the linked list in Java does not necessarily have all the attribute that a Python linked list has.)

1. A list can contain from zero to literally infinitely amount of elements upon definition
2. A list does not necessarily contain a single data type, we can use it to store different data. 

Therefore, the list is more general than a matrix.

There are multiple important attributes we should learn to view and change a list object:
```
# show how many elements in a list
len(b)

# To access the n-th element in a list
b[2] # to get the 3rd element (Python starts from 0)

# Add an extra element at the end of a list
b.append(3)

# Insert an extra element at the n-th position with a value p
b.insert(n, p)

# remove the last element 
b.pop()

# remove the n-th element in a list
b.pop(2)

# find the index of the element with the same value
# note only the first encounter is shown
b.index(2.1)

```

### Exercise 1: 

Try using the above attributes and work on the list `b` by doing the following:
1. Declare a list b with the same set of element as above
2. Remove the last element 
3. Insert the element "apple" at the 3rd position
4. Find the index of the element with value 2.1
5. Find the total number of elements

If it is new to you, you should use the `print` function to output the updated list to see if it really works out correctly. 

In [ ]:
# Declare the list b with the same set of element as above (one line)


# Remove the last element (one line)


# Insert the element "apple" at the 1st position (one line)


# Find the index of the element with a value 2.1 (one line)


# Find the total number of elements (one line)




> https://docs.python.org/3/tutorial/datastructures.html     
> In Python list (and array) indices start with 0, in Matlab they start with 1

# List slicing

How about accessing more than one elements? In that case, we call it slicing the list. To do so, similar to how we use the range object, we define the starting value, stopping value, and the step (if necessary).

For example, let's construct an integer list
`c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]`

If we want to generate a subset of that list, which contains only elements 3 to 8 (without creating a new one), then we can type
```
c[3:9]
```
Again, Python does not return the last element, so we set the ending value as 9 so that the last element is 8, which is what we want.

Then how about if we only want the even number elements (i.e. 0, 2, 4, ...) from the list *c*? To get them, we type
```
c[::2]
```

When there is no parameter supplied to the required position, Python assumes the default value, i.e. as starting value 0, as ending value the last element in the list, and a step of value 1.

In Python, the negative index is defined to be counting backward from the end of the list. For example, `c[-1]` refers to the last element. 

In [40]:
c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(c[3:9])
print(c[::2])

[3, 4, 5, 6, 7, 8]

[0, 2, 4, 6, 8, 10]


In [41]:
# a tricky example
c[-1:-3:-1]

[11, 10]

In [42]:
# reversing the array
c[::-1]

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Using list slicing, we can construct more complicated subsets of a list, by concatenate multiple lists by the '+' operation. 

For example
```
a1 = [0, 2, 4]
a2 = [1, 3, 5]
```
then 
```
a = a1 + a2
```
will generate a new list *a* so that `a = [0, 2, 4, 1, 3, 5]`. Notice that the order of the elements matters during concatenate operation. 

### Exercise 2

Below we declare two subsets of the original big list and then join them. Run this block to see the new list d. Before running it, just count in your mind, how many elements will be in the new list? 

In [17]:
d1 = c[:2]
d2 = c[7:10]

d = d1 + d2
print(d)

### Exercise 3

Consider the list `e = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]`. Build a new list based on the following operations:

1. Add the element 13 to the end of the list
2. Remove the element 0 from the list
3. Generate a subset list e1 which contains all the multiples of 3
4. Generate another subset list `e2` which contains all the multiples of 4
5. Combine the two lists `e1` and `e2` and form a new list `f`

Again you might want to output the list after each step to make sure you are on the right track.

In [1]:
# declare the list e (one line)


# Add the element 13 to the end of the list (one line)


# Remove the element 0 from the list (one line)


# Generate a subset list e1 which contains all the multiples of 3 (one line)


# Generate another subset list e2 which contains all the multiples of 4 (one line)


# Combine the two lists e1 and e2 and form a new list f (one line)




### Nested List

If a list can contain different data types, you might wonder if a list can contain some elements that are itself list objects, then we are forming literally a multi-dimensional array (aka matrix). The answer is yes and no. **Yes**, because if we look at the data stored, that final object indeed looks like a matrix. **No**, because there is no correspondence bewtween many matrix operations and operatinos for nested lists. What's worse is that in terms of computation efficiency, lists are slow. This is because it allocates memory dynamically, and therefore does not aim at storing data efficiently to begin with. You may continue to extend the size of each row or column element. Numpy arrays assume a fixed size, so memory access can be done much more efficienctly. Unless we only use a list once and for all, we encourage you to use Numpy arrays when your main operations are matrix manipulation. 

For completeness we briefly explain the structre of a 2D list (3D lists can be extended similarly)
```
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
```

To address an element, we call from the outer list, to the inner list. For example, the element 
`a[2][1]` is 7, because `a[2]` corresponds to the element `[6,7,8]` and among which the position 1 stands for the second element, i.e. 7. 

### Exercise 4

For the same array, what is the location of the elements '5' and '1'? Check your results in the block below. 

An important use of lists is list comprehension. We can construct a list by a single command, the concept is the same as using a function. Based on a list of input values, we output another list of vaues. This provides much convenience as we will not want to type the entire array by hand which contains, for example, the first 1000 integer numbers. 

There are multiple ways to do so.
1. By using iterables
2. By implicitly using a list

I assume you are familiar with the first method because of the `range` method. It is one of the examples of an iterable. An iterable is an object which can return you one element, sequentially, from its "bag". To construct, for example, a simple integer list, we can type
```
a = [i for i in range(1000)]
```

Then we generate a list containing all integer from 0 to 999 in one line. But how to intepret the syntax? Let's read it from the right to the left. 

The command `range(1000)` creates a bag of integers from 0 to 999. In this bag, Python takes the numbers one by one in ascending order and stores it as *i* (the middle *i*). Then Python forms a list by using all these output numbers directly (the left *i*).  

### Exercise 5:

Create an integer list where it stores the first 1000 odd numbers with the smallest one being 3. What is the 385th element?

The second way is to generate a new list from an existing list. Let us define a similar array `bs`. We can use it to map to another list `cs` which are the first 1000 multiples of 3. 

```
bs = [i for i in range(1,1001)]
cs = [3*b for b in bs]
```

The first declaration for `bs` is the same as above, so we do not explain it again. How about the second declaration? Again we read it from right to left. This time we used the list `bs` as the template, and Python takes out each element one by one and stores as `b`. Then Python constructs a new list where each element has exaclty the value *3b*. 

We remind that a good habit in naming variables in Python is that we use the plural form to represent list object variables and singular form for other ordinary type variables.

In [20]:
bs = [i for i in range(1,1001)]
cs = [3*b for b in bs]

# show the first 5 elements in cs
cs[:5]

[3, 6, 9, 12, 15]

### Exercise 6:

By using list comprehension, create a list with 100 elements where each element is the square of integers, starting from 1. What is the 25th element?

### Lists and for-loops

A list can have the same functionality as an iterable when it comes to a for-loop. Recall that the `range` method is good for creating integer list with fixed interval. How about a list with non-fixed interval? What can we do to ask Python to loop through elements we specifically want? Let us for example, create a list of prime numbers: `primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]`

We can loop through all these elements by replacing the "bags" of numbers from range, namely
```
for i in primes:
    print(i)
```

This is useful if we have to do site-specific operations in a matrix. 

### Exercise 7

Construct a list `c1` with positive odd number integers, starting from 1, with 100 elements. Then construct the following lists by using the list `c1`:

1. A list `c2` which contains squared numbers 
2. Construct a list `c3` of 5 elements which comes from the i-th element in `c2`, where *i* is the first five elements in `c1`
i.e. `c3 = [c2[1], c2[3], c2[5], c2[7], c2[9]]`

Of course you should not explicitly define the list like I show here. Use list comprehension. 

In [ ]:
# Declare c1 (one line)


# Declare c2 (one line)


# Declare c3 (one line)


# check c3 is indeed the elements we need (one line)


> [https://stackoverflow.com/questions/509211/understanding-slice-notation](https://stackoverflow.com/questions/509211/understanding-slice-notation)

## From lists to Numpy arrays

Numpy (Numerical Python) is one of the core infrastructure in the ecosphere of Python libraries. Many upper-level libraries, such as Pandas, Matplotlib, are built on top of it, that means they use the functions and methods for operations in these libraries. Therefore, mastering basic operations in Numpy can help us appreciate the more advanced operations in these libraries. 

In Numpy, specific for this course, the main focus is on the Numpy array, which is essentially the matrix. A Numpy array is different from the nested list by the following.

1. A Numpy array has a fixed size. We cannot directly append or remove an element to change the array size.
2. A Numpy array expects all data has the same data type for maximum efficiency. 
3. A Numpy array has operations such as transpose, matrix multiplication to use. 
4. A Numpy array supports broadcasting where we can add / multiply a scalar or a vector to an entire matrix (with the array size correctly matched).
5. A Numpy array supports slicing along row and column. 

To build a Numpy array, we can directly change a list into an array by the method `numpy.array([...])` which converts the passing parameters into an array. For example, 
```
import numpy as np
a = [0, 1, 2, 3, 4]
a_array = np.array(a)
```

We can check that `a` and `a_array` are of different data type:

In [3]:
import numpy as np

a = [0, 1, 2, 3, 4]
a_array = np.array(a)

print(type(a), type(a_array))

<class 'list'> <class 'numpy.ndarray'>


In [26]:
print(a)
print(a_array)

[0, 1, 2, 3, 4]

[0 1 2 3 4]


We may notice that the output format in a list and an array is different. 

We can also directly allocate a zero or unity array and populate it by other means. 

```
a_zeros = np.zeros((2,3))
a_ones = np.ones((2,3))
```

The array `a_zeros` gives you an array of 2 rows and 3 columns, with all elements zero. Similar `a_ones` is an array with all elements one. It sufficies to say that the first index is the row number and the second index is the column number.  

In [4]:
a_z = np.ones((2,3))
a_z

array([[1., 1., 1.],
       [1., 1., 1.]])

To call an element in a numpy array, we need to use the double index, instead of two separate indices as in a list. For example

```
a = [[1,2,3], [4,5,6], [7,8,9]]
a_array = np.array(a)
```

To call one of the element, let's say the element 7, we use `a_array[2,0]`.

We can also slice a matrix to get a row or column vector by using the colon (:) to indicate an entire dimension. We can also plug in specific numbers similar to how we slice a list. 

In [6]:
# note that you don't have to import the numpy library again if you have done already
# I provide it in case you start from this part of the notes
import numpy as np

a = [[1,2,3], [4,5,6], [7,8,9]]
a_array = np.array(a)

a_row = a_array[0,:]
a_col = a_array[:,1]

print(a_row)
print(a_col)

[1 2 3]
[2 5 8]


>https://numpy.org/doc/stable/reference/arrays.indexing.html

We observe that Numpy converts the slice into a row vector. 

Numpy array is a class. So, similar to Java, we use methods to extract the properties of the array. For example, we use the attribute `shape` to extract the dimension of the matrix

In [32]:
print(a_array.shape)
print(a_row.shape)

(3, 3)

(3,)


Side note: You may notice that in both cases Numpy returns a *tuple* instead of a single number. We can retrieve the size of row or column of a matrix by its index as in a list.

For example: `a_array.shape[0]` gives the row number of `a_array`.

In order to form a column vector, we use the attribute transpose `T` or `transpose` to transpose a matrix or to convert a row (column) vector into a column (row) vector.

In [7]:
a_array_T = a_array.T

print(a_array_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


We can directly do arithmatic operations by adding / subtracting / multiplying all elements with another matrix.

Notice that the multiplication here *is different* from matrix multiplcation (we will cover matrix multiplication below). When you use * to multiply two matrices, Numpy does an element-wise multiplication. 


In [8]:
# Numpy broadcasts the constant to all elements
b1 = a_array + 1
print(b1)

# Numpy broadcasts the row vector to all rows 
b2 = a_array + a_row
print(b2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [9]:
# Numpy broadcasts the columns vector to all columns
b3 = a_array * a_col
print(b3)

# Numpy does an element-wise multiplication
b4 = a_array * a_array_T
print(b4)

[[ 2 10 24]
 [ 8 25 48]
 [14 40 72]]
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]


We need to use the Numpy method `mat_mul` to perform the matrix multiplication. For example


In [10]:
a_mat_mul = np.matmul(a_array, a_array_T)
print(a_mat_mul)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


### Exercise 8
Verify by directly doing the multiplcation by hand to persuade yourself that Numpy is indeed doing  the proper matrix multiplication.

### Exercise 9

Define the following matrices
```
d1 = [[1,2],[3,2]]
d_row = [3,1]
```

Use Numpy and then calculate by pen: d_row$^T \cdot$ d1 $\cdot$ d_row

## Functions

The discussion of a programming language cannot be complete without mentioning how to define a function. Similar to mathematics, a function is a callable method that operates on some input parameters, and then returns the result. Using functions properly can largely simplify our code structure by putting repetitive processes into a separate place, and call them when we need to. It also specifies clearly (by good documentation) the logical flow of the code without displaying all details at once. A good function is when we can reuse the function not only in the same code, but also in other codes. 

There are also functions that do not return anything (aka subroutine) and there are also functions which do not need input parameters. 

To define a function, we use `def` to declare, and then the function name, and the parameter. For example:

```
def get_square(x):
    return x*x
```

In [48]:
def get_square(x):
    return x*x

print("The square of 3 is ", get_square(3))

The square of 3 is  9


A function (unique in Python) can accept more than one input parameter and/or return more than one results. In the following example, the code takes a number (an ideal case is that the code should check the input for its validity), and then returns the next odd and even number. 

In [11]:
def next_odd_and_even(n):
    
    # case 1: n is even
    if n%2==0:
        return n+1, n+2
        
    else:
        return n+2, n+1
        
# test the function
m = 3
next_odd, next_even = next_odd_and_even(m)

# output results in pretty format
print('the input number is ', m)
print('the next odd is ', next_odd)
print('the next even is ', next_even)

the input number is  3
the next odd is  5
the next even is  4


Note that once the method reaches the line with `return`, Python will leave the method and return to the place from where the method is called. The later part of the method, no matter how long, will not be used. 

**Side note**: 
    
We emphasize that in Python the data structure is flexible, so that we can treat the output of a function as a tuple, and then decompress it when we need. This may reduce the number of variables for debugging.

In [12]:
m = 3
next_numbers = next_odd_and_even(m)

# output results in pretty format
print('the input number is ', m)
print('the compact output is ', next_numbers)
print('the next odd is ', next_numbers[0])
print('the next even is ', next_numbers[1])

the input number is  3
the compact output is  (5, 4)
the next odd is  5
the next even is  4


### Exercise 10 (Fibonacci number 1)

Let us build our Fibonacci number generator. It can be tough if it is the first time to code. So we break down the problem into two parts. First, by definition, the Fibonacci number is the sum of the two previous numbers in the series, with the first two number in the series being 0 and 1. So the sequence is (I assume you know it very well) $[0, 1, 1, 2, 3, 5, ...]$.

Our first step is to write a function so that we get the next Fibonacci number when we provide two numbers. 

**Note**: You cannot compile the next block right away without replace `[...]` first, otherwise it will yield error. 

In [13]:
def next_fibo(x1, x2):
    return [...]

In [14]:
# test your results here


### Exercise 11 (Fibonacci number 2)

Now we can find the next Fibonacci number by your new method! The next step is that, if we want to find the n-th Fibonacci number, the next method will use your new method repeatedly. 

Notice that there are special cases in finding the Fibonacci number $F$ (or known as the boundary case), namely when $n = 1$ and $n = 2$. $F(1) = 0$ and $F(2) = 1$ are by definition and cannot be found by your method. Otherwise, if $n > 3$, your method should do the iteration until you get the right $n$. In the method, we define `fibo_1` and `fibo_2` to be the previous two Fibonacci numbers, we use it to find the next Fibonacci number. 

Again, fill in the part with `[...]` to make the code really works the way we designed. 

Note: It can be more compactly done in a recursion but it requires very clear concept in variable management, data flow and boundary case so that the code does not fall into an infinite loop. Therefore, we omit the discussion here and leave for some more advanced course. 

In [16]:
def find_fibo(n):
    
    if [...]: # limit case n = 1
        return [...]
    
    elif [...] # limit case n = 2
        return [...]
    
    else: # if n > 2, do the iteration
        
        fibo_1 = 0
        fibo_2 = 1
        
        # think carefully if we are doing the n-th case
        # how many iteration do we need?
        for i in range([...]): 
            fibo_new = [...]
            
            # now we get the new Fibonacci number
            # So we want to replace the previous 
            # fibo_1 and fibo_2 to the appropriate 
            # values 
            [...]
        
        return fibo_new

In [ ]:
# test your results here
# The 10th Fibonacci number is 34

find_fibo(10)

### Exercise 12 (practice makes perfect)

In the last exercise we gave a very detailed guide on building a method to find the Fibonacci numbers. However, your programming skills cannot grow if you have not gone through the code design and thinking process by yourself. 

This time, based on the idea we have described, try your best not to copy or peep the previous methods, and fill in the method below to build your own Fibonacci number finder. 

In [ ]:
def my_next_fibo(x1, x2):
    [...]
    
def my_find_fibo(n):
    [...]
    

In [ ]:
# test your own version
# do you get the same results as the guided one?

my_find_fibo(10)

### Exercise 13 (prime number search)

Let us write a method to identify if a particular number is a prime number. By definition, a prime number is that the number is not divisible by any positive integer smaller than it except 1. And therefore, 7 is a prime number and 10 is not a prime number because it is divisible by 2 and 5. 

Again, fill in the `[...]` below to make the method working as designed. 

This method directly uses iteration to loop over relevant numbers to check if the input number has any divisible numbers. 

In [ ]:
def is_prime(n):
    
    # we by default assume a number is a prime 
    result = True
    
    # then check the input number by integer
    # smaller than it. How small should it be? (1 line)
    for i in [...]:
    
        # which operator should you use to find if
        # is divisible? (1 line)
        if [...]:
            
            # what will you do if you know the 
            # number is divisible? (1-2 line)
            [...]
    
    
    # return your decision to the code that calls it
    return result    

In [ ]:
# test your method here

print("100 is a prime", is_prime(100))
print("101 is a prime", is_prime(101))

### Scope of a function

In Python, there are two types of variables, global variables and local variables. Global variables, as its name defines, can be accessed anywhere in the code. For example, all the variables, like `a_array` we saw earlier in this chapter, once they are defined outside a function, its value can be used until we close the Python kernel. We call these variables global variables. 

On the other hand, when a variable is defined inside a method, we will not be able to access it after Python leaves the method. We call these variables local variables.

Therefore, when you build a large code without using functions to manage the variables, there is a chance that you accidentially reuse some variable names, and may overwrite what you defined before. This could be a problem if those numbers are essential ones, for example, some mathematical or physical constants.

In the example below, we show how these variables are accessed. The code computes the quadratic equation $y = ax^2 + bx + c$.

In [17]:
a = 3
b = 2
c = 1

def quad_eq(x):   
    y = a*x**2 + b*x + c
    return y

In [18]:
print(quad_eq(3))

34


In [19]:
print(y)

<class 'NameError'>: name 'y' is not defined

Now we see that variable `y` cannot be accessed from outside the method because it is valid only *in* the method. 

Another possible scenario is that if you use the same variable names outside and inside of a method, Python chooses the value that the varaible has inside the method (override). For new programmer, we do not encourage this unless you have a clear code map of how the data flow takes place. 

> [https://docs.python.org/3/library/__main__.html](https://docs.python.org/3/library/__main__.html)

### Passing by Reference and Passing by Value

An important concept in function is that Python distinguishes the two types of passing into a function or a method. This distinction is common in other languages, including C and C++, but not so for some langunages, such as Fortran. Python, by default, assumes both types of passing depending on the data type. 

- Passing by **value**: Only the **value** of the variable is passed intto a method. 
- Passing by **reference**: The **address** of the object is passed into a method. 


But why the address or the value important in passing the variables? The answer is, sometimes in the function, we might, intentionally or inadvertently, modify the variables coming from the main program. If the variables is passed by reference, the modification remains there after Python finishes the function. On the other hand, the modification is only valid for passing by value. 

The exact passing method depends on the data type:
- Passing by **value**: Boolean, integer, floating point
- Passing by **reference**: String, other objects

Let us take a look at the example below to see why it is important:

In [3]:
int_var = 1
list_var = [1, 2, 3]

def operation(int_var, list_var):
    int_var = 5
    list_var[0] = 5
    
    print("Inside the function, a = ", int_var)
    print("Inside the function, c = ", list_var)

In [4]:
operation(int_var, list_var)
print("After operation: ")
print("Outside the function, a = ", int_var)
print("Outside the function, c = ", list_var)

Inside the function, a =  5
Inside the function, c =  [5, 2, 3]
After operation: 
Outside the function, a =  1
Outside the function, c =  [5, 2, 3]


### Exercise 14 (code study)

In the code below, if you run it, the result is different from what we expect. We want to calculate $y=f(x)=3x^2 + 2x + 1$ and then double the coefficients, so that the next time we will have $y=f(x)=6x^2 + 4x + 2$. But it seems it is not done. 

Can you fix it?

In [7]:
a = 3
b = 2
c = 1

def quad_eq2(a, b, c, x):   
    
    # get the product (c, bx and ax^2)
    y = a*x**2 + b*x + c
    
    # modify the coefficient
    a *= 2
    b *= 2
    c *= 2
    
    return y

In [13]:
quad_eq2(a, b, c, 1)
print("The modified coefficients are a = {}, b = {}, c = {}".format(a,b,c))

The modified coefficients are a = 3, b = 2, c = 1


## Case study: LU decomposition (By Andrea)

Homework 1 asks you to solve a system of linear equations Ax=b, using the LU decomposition.

In the code below, we build two methods. The *main* method which we use to test the LU decomposition method, and the LU decomposition method itself. 


In [ ]:
''' 
MAT 460, HW 1ab, Author, Date

Solve Ax=b using LU decomposition
(1) A=LU, (2) solve Ly=b, (3) solve Ux=y

Testcase: Ax=b has solution x = [1,2,3]^T 
for
L = np.array([[1,0,0],[-2,1,0],[4,5,1]])
U = np.array([[2,-1,6],[0,3,9],[0,0,-2]])
b = np.array([18,-3,231])
'''

import numpy as np 
import scipy.linalg as la     # what is this?

def main(): 

    # (2) solve Ly=b
    L = np.array([[1,0,0],[-2,1,0],[4,5,1]])
    b = np.array([18,-3,231])
    y = my_forward(L,b)
    # compare with python linear algebra library solver
    print(y,"=?=",la.solve(L,b))
    
    # example from hwset 1 
    U = np.array([[2,-1,6],[0,3,9],[0,0,-2]])
    A = np.dot(L,U)
    print(A)
    
    x = la.solve(A,b)
    print(x)
    
    
# function definitions start  
def my_forward(L,b):
    ''' solve lower triangular system: Ly = b
    for k = 0...n-1         
       b_k = y_k
       for j = 0...k 
          y_k = y_k - l_kj y_j
    '''
    n = L.shape[0]
    y = np.zeros(n)        
    for k in range(n):         
        y[k] = b[k]
        for j in range(k):      
            y[k] = y[k] - L[k,j]*y[j]             
    return y


if __name__ == "__main__":
    main()     

Develop the algorithm for the backward solver. Over which index pairs do we have to loop? Write the pseudo-code for this function.
Change the following piece of code so that these 2 for-loops give the number pairs (k,j) = (2,2), (1,1), (1,2), (0,0), (0,1), (0,2).

In [64]:
n = 3
for k in range(n,-1,1):
    for j in range(k+1,n):
        print(k,j)

### Exercise 15 (backward decomposition)

```
# TODO
#def backward(U,y):
#    return x

# make hw easier, we allow using python to do the A=LU
#def myLU(A):
#    return L,U
```

The remaining task is to fill in the two methods so that we complete the diagonalization. Please refer to your homework assignment. 

## PEPs and more in-depth Python tutorials

> The [Zen of Python](https://www.python.org/dev/peps/pep-0020/) and [Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#other-recommendations)

> [https://docs.python-guide.org/](https://docs.python-guide.org/)

> [https://docs.python-guide.org/intro/learning/](https://docs.python-guide.org/intro/learning/)

> [http://www.davekuhlman.org/python_book_01.html](http://www.davekuhlman.org/python_book_01.html)

<font color='purple'> What are PEPs? Give 3 examples for good coding style.  
I liked Kuhlman's book. It has 3 parts: Beginning, Advanced, and Exercises with Solutions (''for those who feel a need for less explanation and more practical exercises'').</font>