# Python Review Crash Course - Part II

## Data Structures (Lists and other Sequences), Numpy Arrays, Functions, PEPs

Minor edits by Andrea in Jan 2026

Developed by Shing Chi Leung in Jan 2023 &#128512;

Based on the course structure developed by Andrea Dziubek



## List object, operation and iterable

In Lecture 1 we have touched the concept of a list, which is an object. This is an important and flexible data structure which has extremely wide use. There are other important data structure that we will not have time to explore, for example `dict`, `tuple`, and `set`. These will be useful for data science use or development of software beyond mathematics. 

In Python when we construct a list, we are creating a list *object* to work on. To declare a list object, we type
```
# this generates an empty list
a = [] 

# this generates a list with 4 elements
b = [1, 2.1, 'a', True] 
```

It suffices to observe two features in a Python list. (Notice: the exact properties of a (linked) list depend on the language. For example the linked list in Java does not necessarily have all the attribute as a Python linked list.)

1. A list can contain from zero to literally infinitely amount of elements upon definition.
2. A list does not necessarily contain single data type, we can use it to store different data. 

Therefore, the list is more general than a matrix.

There are multiple important attributes we should learn to view and change a list object:
```
# show how many elements in a list
len(b)

# To access the n-th element in a list
b[2] # to get the 3rd element (Python starts from 0)

# Add an extra element at the end of a list
b.append(3)

# Insert an extra element at the n-th position with a value p
b.insert(n, p)

# remove the last element 
b.pop()

# remove the n-th element in a list
b.pop(2)

# find the index of the element with the same value
# note only the first encounter is shown
b.index(2.1)

```

### Exercise 1: 

Try using the above attributes and work on the list `b` by doing the following:
1. Declare the list b with the same set of element as above
2. Remove the last element
3. Insert the element "apple" at the 3rd position
4. Find the index of the element with a value 2.1
5. Find the total number of elements

If it is new to you, you should use the `print` function to output the updated list to see if it really works out correctly. 

In [62]:
# Declare the list b with the same set of element as above (one line)
b = [1, 2.1, 'a', True] 
print(b)

# Remove the last element (one line)
b.pop()
print(b)

# Insert the element "apple" at the 1st position (one line)
b.insert(2, 'apple')
print(b)

# Find the index of the element with a value 2.1 (one line)
print(b.index(2.1))

# Find the total number of elements (one line)
print(len(b))

#help(list)

[1, 2.1, 'a', True]
[1, 2.1, 'a']
[1, 2.1, 'apple', 'a']
1
4


Then how about accessing more than one elements? In that case, we call it **slicing** the list. This is similar to how we used the range object, we define the starting value, stopping value, and the step (if necessary)

For example, let's construct an integer list
`c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]`

If we want to generate a subset of the list, which contains only 3 to 8 (without creating a new one), we can type
```
c[3:9]
```
Again, Python does not return the last element, so we set the ending value as 9 so that the last element is 8, which is what we want.

Then how about if we only want the even number elements (i.e. 0, 2, 4, ...) from the list *c*. to do so, we type
```
c[::2]
```

When there is no parameter provided at the required position, Python assumes the default value, i.e. for starting value 0, ending value to be the last element in the list, and step of value 1.

In Python, the negative index is defined to be counting backward from the end of the list. For example, `c[-1]` refers to the last element. 

In [9]:
c = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(c)
print(c[3:9])
print(c[::2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [3]:
# a tricky example
print(c)
c[-1:-3:-1]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


[11, 10]

In [4]:
# reversing the array
c[::-1]

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

By using list slicing, we can construct a more complicated list by **concatenating** multiple lists using the '+' operation. 

For example
```
a1 = [0, 2, 4]
a2 = [1, 3, 5]
```
then 
```
a = a1 + a2
```
will generate a new list *a* so that `a = [0, 2, 4, 1, 3, 5]`. Notice that the order of the elements matter during concatenate operation. 

### Exercise 2

Below we declare two subsets of the original big list and then join them. Run this block to see the new list d. Before running the code,    
**how many elements will be in the new list?** 

In [6]:
print(c)
d1 = c[:2]
d2 = c[7:10]

#d = d1 + d2
#print(d1)
#print(d2)
#print(d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


### Exercise 3

Consider the list `e = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]`. Build a new list based on the following operations:

1. Add the element 13 to the end of the list
2. Remove the element 0 from the list
3. Generate a subset list e1 which contains all the multiples of 3
4. Generate another subset list `e2` which contains all the multiples of 4
5. Combine the two lists `e1` and `e2` and form a new list `f`

Again you might want to output the list after each step to make sure you are on the right track.

In [12]:
# declare the list e (one line)

e = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
# Add the element 13 to the end of the list (one line)
e.append(13)
print(e)

# Remove the element 0 from the list (one line)
e.pop(0)
print(e)

# Generate a subset list e1 which contains all the multiples of 3 (one line)
e1 = e[2::3]
print(e1)

# Generate another subset list e2 which contains all the multiples of 4 (one line)
e2 = e[3::4]
print(e2)

# Combine the two lists e1 and e2 and form a new list f (one line)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[3, 6, 9, 12]
[4, 8, 12]


### Nested List

If a list can contain different data type, you might wonder if some elements of a list can be list objects, then we are forming literally a multi-dimensional array (aka matrix). The answer is yes and no. **Yes** is that by means of data stored, that final object indeed looks like a matrix. **No** is that there is no correspondence to many matrix operations for a nested list. What's worse is that in terms of computation efficiency, list operations are slow. This is because it uses a dynamic memory allocation approach, and therefore does not aim at storing data efficiently to begin with. You may continue to extend the size of each row or column element. **Numpy arrays** have a fixed size, so memory access is much more efficienct. Unless we only use the list once and for all, we encourage you to use Numpy array when your main operation is matrix manipulation. 

For completeness we briefly explain the structre of a 2D list (3D list can be extended similarly)
```
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
```

To address the element, we call from the outer list, to the inner list. For example, if the element 
`a[2][1]` is 7, because `a[2]` corresponds to the element `[6,7,8]` and among which the position 1 stards for the second element, i.e. 7. 

### Exercise 4

From the same array, what is the location for the element '5' and '1'? Check your results by the block below. 

In [15]:
a = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
print(a[1][2])
print(a[0][1])

5
1


An important use of lists is **list comprehension.** We can construct a list by a single command, the concept is the same as a function. Based on a list of input values, we output another list of values. This is very convenienient, as we would not want to type by hand the entire array of, for example, the first 1000 integers. 

There are multiple ways to do this.
1. By using **iterables**
2. By implicitely generating a list from another list

The `range` method is an iterable. An iterable is an object which returns one element, sequentially, from its "bag". To construct, for example, a simple integer list, we can type
```
a = [i for i in range(1000)]
```

We just generated a list containing all integers from 0 to 999 in one line. But how to intepret the syntax? Let's read it from the right to the left. 

The command `range(1000)` creates a bag of integers from 0 to 999. In this bag, `for i in range(1000)` takes the numbers one by one in ascending order and stores it as *i* (the middle *i*). Then Python forms a list by using all these output number directly (the left `i`).  

### Exercise 5:

Create an integer list that stores the first 1000 odd numbers, starting with 3. What is the 385th element?

In [23]:
a = [i for i in range(1000)]
a = a[3::2]
#print(a[384])
#len(a)

The second way is to generate a new list from an existing list. Let us define a similar array `bs`. We can use it to map to another list `cs` which contains the first 1000 multiples of 3. 

```
bs = [i for i in range(1,1001)]
cs = [3*b for b in bs]
```

The first declaration for `bs` is the same as above. Then how about the second declaration. Again we read it from right to left. We use the list `bs` as the template, and Python takes out each element one by one and stores them as `b`. Then Python constructs a new list where each element has the value *3b*. 

We remind that a good habit in naming variables in Python is that we use plural form to represent list object variables and singular form for other ordinary type variables.

In [24]:
bs = [i for i in range(1,1001)]
cs = [3*b for b in bs]

# show the first 5 elements in cs
#cs[:5]

### Exercise 6:

By using list comprehension, create a list with 100 elements where each element is the square of integers, starting from 1. What is the 25th element?

In [28]:
a = [i**2 for i in range(1,101)]
print(a)
len(a)
#print(a[24])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]


100

### Use of list for a for loop

The list can have the same functionality as an interable when it comes to a for-loop. Recall that the `range` method is good for creating integer lists with a fixed interval. How about a list with non-fixed interval? What can we do to ask Python to loop for elements we specifically want? Let us for example, create a list of prime numbers: `primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]`

We can loop through all these elements by replacing the "bags" of number from range, namely
```
for i in primes:
    print(i)
```

This is useful if we have site-specific operation in a matrix. 

### Exercise 7

Construct a list `c1` with positive odd number integers starting from 1 with 100 elements. Then generate the following lists from the list `c1`:

1. A list `c2` which contains squared numbers 
2. A list `c3` of 5 elements which come from the i-th element in `c2`, where *i* is the first five elements in `c1`
i.e. `c3 = [c2[1], c2[3], c2[5], c2[7], c2[9]]`

Of course you should not explicitly define the list as what I show here. Use list comprehension. 

In [29]:
# Declare c1 (one line)
c1 = [i for i in range(1,201)]
c1 = c1[::2]
print(c1)
print(len(c1))

# Declare c2 (one line)
c2 = [i*i for i in c1 ]
print(c2)
print(len(c2))

# Declare c3 (one line)


# check c3 is indeed the elements we need (one line)


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]
100
[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841, 961, 1089, 1225, 1369, 1521, 1681, 1849, 2025, 2209, 2401, 2601, 2809, 3025, 3249, 3481, 3721, 3969, 4225, 4489, 4761, 5041, 5329, 5625, 5929, 6241, 6561, 6889, 7225, 7569, 7921, 8281, 8649, 9025, 9409, 9801, 10201, 10609, 11025, 11449, 11881, 12321, 12769, 13225, 13689, 14161, 14641, 15129, 15625, 16129, 16641, 17161, 17689, 18225, 18769, 19321, 19881, 20449, 21025, 21609, 22201, 22801, 23409, 24025, 24649, 25281, 25921, 26569, 27225, 27889, 28561, 29241, 29929, 30625, 31329,

## From list to Numpy array

Numpy (Numerical Python) is one of the core infrastructure in the ecosphere of Python libraries. Many upper-level libraries, such as Pandas, Matplotlib, are built on top of it, that means they use the functions and methods for operations in these libraries. Therefore, mastering basic operation in Numpy can help us appreciate the more advanced operations in these libraries. 

In Numpy, the main focus is the Numpy array, which is an array of array, i.e. a matrix. A Numpy array is different from a nested list.

1. Numpy arrays have a fixed size. We cannot directly append or remove to change the array size.
2. Numpy arrays expect that all data have the same data type for maximum efficiency. 
3. Numpy arrays come with operations such as transpose, matrix multiplication that we can  use. 
4. Numpy arrays support broadcasting, where we can add / multiply a scalar or vector to an entire matrix (with the array size correctly matched).
5. Numpy arrays support slicing along row and column. 

To build a Numpy array, we can directly change a list into an array by the method `numpy.array([...])`. This will cast the passing parameters into an array. For example, 
```
import numpy as np
a = [0, 1, 2, 3, 4]
a_array = np.array(a)
```

We can check that `a` and `a_array` are of different data types.

In [15]:
import numpy as np

a = [0, 1, 2, 3, 4]
a_array = np.array(a)

print(type(a), type(a_array))

<class 'list'> <class 'numpy.ndarray'>


In [16]:
print(a)
print(a_array)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


We may notice that the output format in a list and an array is different. 

We can also directly allocate a zero or unity array and populate it by other means. 

```
a_zeros = np.zeros((2,3))
a_ones = np.ones((2,3))
```

The array `a_zeros` gives you an array of 2 rows and 3 columns, with all elements zero. Similar `a_ones` is that with all elements one. It sufficies to say that the first index is the row number and the second index is the column number.  

In [17]:
a_z = np.ones((2,3))
print(a_z)
print(type(a_z))

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


To call an element in a numpy array, we need to use the double index, instead of two separate indices as in a list. For example

```
a = [[1,2,3], [4,5,6], [7,8,9]]
a_array = np.array(a)
```

To call one of the element, let's say the element 7, we use `a_array[2,0]`.

We can also slice a matrix to get a row or column vector by using colon (:) to indicate the entire dimension. We can also plug in specific numbers, similar to how we sliced a list. 

In [1]:
# You don't need to import the numpy library again if you did this earlier  
# Only in case you start from this part of the notes
import numpy as np

a = [[1,2,3], [4,5,6], [7,8,9]]
a_array = np.array(a)

a_row = a_array[0,:]
a_col = a_array[:,1]

print(a_array)
print(a_row)
print(a_col)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[2 5 8]


We observe that Numpy converts a slice into a row vector. 

A numpy array is a class. So, similar to Java, we can use a method to extract the properties of the array. For example, we use the attribute `shape` to extract the dimension of the matrix

In [2]:
print(a_array.shape)
print(a_row.shape)
print(a_col.shape)

(3, 3)
(3,)
(3,)


Side note: You may notice in both cases Numpy returns a *tuple* instead of a single number. We can retrieve the size of row or column of a matrix by the index as in a list.

For example: `a_array.shape[0]` to get the row number of `a_array`.

In order to form a column vector, we can use the attribute transpose `T` or `transpose` to transpose a matrix or to convert a row (column) vector into a column (row) vector.

In [3]:
a_array_T = a_array.T

print(a_array_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


We saw that Numpy slices a vector into an array, aka a row vector. To convert an array into a column vector we can use  *newaxis*. It increases the dimension of the numpy array by one and casts the elements of the array into the new shape.

In [14]:
a_col_T = a_col[:,np.newaxis]
print(a_col.shape, '\n', a_col)
#print(a_col_T.shape, '\n', a_col_T)

(3,) 
 [2 5 8]


Then we can directly do arithmetic operations by adding / subtracting / multiplying all elements with another matrix.

Notice that the multiplication here *is different* from matrix multiplication (we will cover matrix multiplication below). When you use * to multiply two matrices, Numpy does an element-wise multiplication. 


In [15]:
# Numpy broadcasts "+1" to all elements
b1 = a_array + 1
#print(b1)

In [16]:
# Numpy broadcasts "add row 1" to all rows 
#print(a_array)
print(a_row)
b2 = a_array + a_row
#print(b2)

[1 2 3]


In [17]:
# Numpy broadcasts "multiply by column 1" to all columns
b3 = a_array * a_col
#print(b3)

In [18]:
# Numpy does an element-wise multiplication 
b4 = a_array * a_array_T
#print(b4)

We need to use the Numpy method `matmul` to calculate the matrix multiplication. The operator `@` is the shortcut for this operation and is the standard way to do a matrix multiplication. 

In [19]:
a_matmul = np.matmul(a_array, a_array_T)
print(a_matmul)
print()

a_mat_mul_T = a_array @ a_array_T
print(a_mat_mul_T)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


### Exercise 8
Verify by doing the multiplication by hand to persuade yourself that Numpy is indeed doing the proper matrix multiplication.

### Exercise 9

Define the following matrices
```
d1 = [[1,2],[3,2]]
d_row = [3,1]
```

Use Numpy to calculate d_row$^T \cdot$ d1 $\cdot$ d_row, and check the result by pen. 

In [29]:
import numpy as np

d1 = np.array([[1,2],[3,2]])
d_row = np.array([3,1])
d_col = d_row[:,np.newaxis]

print(d1)
print(d_row)
print(d_row.shape)
print(d_col.shape)
print()

er = d1 @ d_row
#print(er)

ec = d1 @ d_col
#print(ec)

s = d_row @ d1 @ d_col
#print(s)

c = d_row @ d1 @ d_row.T
#print(c)

[[1 2]
 [3 2]]
[3 1]
(2,)
(2, 1)



We see that for numpy, everything is an array. So we can also first perform the matrix multiplication and then cast the resulting array (row vector) into a column vector, if we really need a column vector.

In [2]:
import numpy as np

A = np.array([[1, 2],
              [3, 2]])

b = np.array([3, 1])

C = A @ b

#print(C)

## Functions

The discussion of a programming language cannot be complete without mentioning how to define a function. Similar to mathematics, a function is a callable method that operates on some input parameters, and then returns the product. Using functions properly can largely simplify our code. It adds structure by putting repetitive processes into a separate place, and call them when we need to. It also specifies clearly (by good documentation) the logical flow of the code without displaying all details at once. A good function is one that we can reuse, not only in the same code, but also in other codes. 

There are also functions that do not return a value (aka subroutine) and functions which do not need input parameters. 

To define a function, we use `def` to declare the function, followed by the function name, with the parameters (in brackets). For example:

```
def get_square(x):
    return x*x
```

In [13]:
def get_square(x):
    return x*x

print("The square of 3 is ", get_square(3))

The square of 3 is  9


A function (unique in Python) can accept more than one input parameter and/or return more than one results. In the following example, the code takes a number (an ideal case is that the code should check the input for its validity), and then returns the next odd and even number. 

In [14]:
def next_odd_and_even(n):
    
    # case 1: n is even
    if n%2 == 0:
        return n+1, n+2
        
    else:
        return n+2, n+1
        
# test the function
m = 3
next_odd, next_even = next_odd_and_even(m)

# output results in pretty format
print('the input number is ', m)
#print('the next odd is ', next_odd)
#print('the next even is ', next_even)

the input number is  3


A reminder is that once the method reaches the line with `return`, Python will leave the method and return to the place where the method is called. The later part of the method, no matter how long, will not be used. 

**Side note**: 
    
We emphasize that in Python the data structure is flexible, we can treat the output of a function as a tuple, and then decompress it when we need. This may reduce the number of variables for debug.

In [15]:
m = 3
next_numbers = next_odd_and_even(m)

# output results in pretty format
print('the input number is ', m)
print('the compact output is ', next_numbers)
print('the next odd is ', next_numbers[0])
print('the next even is ', next_numbers[1])

the input number is  3
the compact output is  (5, 4)
the next odd is  5
the next even is  4


### Exercise 10 (Fibonacci number 1)

Let us build a Fibonacci number generator. This can be tough for a beginner. So we break down the problem into two parts. First, by definition, the Fibonacci numbers are the sum of the two previous numbers in the series, with the first two number in the series being 0 and 1. So the sequence is (I assume you know it well) $[0, 1, 1, 2, 3, 5, ...]$.

Our first step is to write a function that gives us back the next Fibonacci number when we provide two previous Finumbers. 

**Note**: You cannot compile the next block right away without replace `[...]` first, otherwise it will yield error. 

In [4]:
def next_fibo(x1, x2):
    return [...]

In [5]:
# test your results here
z = next_fibo(0,1)

print(z)

[Ellipsis]


### Exercise 11 (Fibonacci number 2)

Now we can find the next Fibonacci number by your new method! The next step is that, if we want to find the n-th Fibonacci number, the next method will use your new method repeatedly. 

Notice that there are special cases in finding the Fibonacci number $F$ (or known as the boundary case), namely when $n = 1$ and $n = 2$. $F(1) = 0$ and $F(2) = 1$ are by definition and cannot be found by your method. Otherwise, if $n > 3$, your method should do the iteration until you get the right $n$. In the method, we define `fibo_1` and `fibo_2` to be the previous two Fibonacci numbers, we use it to find the next Fibonacci number. 

Again, fill in the part with `[...]` to make the code really works the way we designed. 

Note: It can be more compactly done in a recursion but it requires very clear concept in variable management, data flow and boundary case so that the code does not fall into an infinite loop. Therefore, we omit the discussion here and leave for some more advanced course. 

In [28]:
def find_fibo(n):
    
    if n==1: # limit case n = 1
        return 1
    
    elif [...] # limit case n = 2
        return [...]
    
    else: # if n > 2, do the iteration
        
        fibo_1 = 0
        fibo_2 = 1
        
        # think carefully if we are doing the n-th case
        # how many iteration do we need?
        for i in range([...]): 
            fibo_new = [...]
            
            # now we get the new Fibonacci number
            # So we want to replace the previous 
            # fibo_1 and fibo_2 to the appropriate 
            # values 
            [...]
        
        return fibo_new

SyntaxError: expected ':' (691705004.py, line 6)

In [29]:
# test your results here
# The 10th Fibonacci number is 34

find_fibo(10)

NameError: name 'find_fibo' is not defined

### Exercise 12 (practice makes perfect)

In the last exercise we give a very detailed guide in building a method to find the Fibonacci number. However, your programming skills cannot grow if you have not go through the code design and thinking process by yourself. 

This time, based on the idea we have described, try your best not to copy or peep the previous methods, and fill in the method below to build your own Fibonacci number finder. 

In [30]:
def my_next_fibo(x1, x2):
    [...]
    
def my_find_fibo(n):
    [...]
    

In [31]:
# test your own version
# do you get the same results as the guided one?

my_find_fibo(10)

### Exercise 13 (prime number search)

Let us write a method to identify if a particular number is a prime number. By definition, a prime number is that the number is not divisible to any positive integer smaller than it except 1. And therefore, 7 is a prime number and 10 is not a prime number because it is divisible by 2 and 5. 

Again, fill in the `[...]` below to make the method works as designed. 

This method directly uses iteration to loop over relevant numbers to check if the input number has any divisible numbers. 

In [32]:
def is_prime(n):
    
    # we by default assume a number is a prime 
    result = True
    
    # then check the input number by integer
    # smaller than it. How small should it be? (1 line)
    for i in [...]:
    
        # which operator should you use to find if
        # is divisible? (1 line)
        if [...]:
            
            # what will you do if you know the 
            # number is divisible? (1-2 line)
            [...]
    
    
    # return your decision to the code that calls it
    return result    

In [33]:
# test your method here

print("100 is a prime", is_prime(100))
print("101 is a prime", is_prime(101))

100 is a prime True
101 is a prime True


### Scope of function

In Python, there are two types of variables, global variables and local variables. Global variables, as its name defines, can be accessed in anywhere in the code. For example, all the variables, like `a_array`, that we saw earlier in this chapter, once they are defined outside a function, its value can be used until we close the Python kernel. We call these variables global variables. 

On the other hand, when the variable is defined inside a method, we will not be able to access it after Python leaves the method. We call these variables local variables.

Therefore, when you build a large code without using functions to manage the variables, there is a chance that you reuse some variable names, and it may overwrite what you defined before. This could be a problem if those numbers are essential one, for example, some mathematical or physical constants.

In the example, below, we show how these variables are accessed. The code computes the quadratic equation $y = ax^2 + bx + c$.

In [8]:
a = 3
b = 2
c = 1

def quad_eq(x):  
    a = 5
    y = a*x**2 + b*x + c
    return y

In [25]:
print(quad_eq(3))

52


In [9]:
print(a)
print(y)

3


NameError: name 'y' is not defined

Now we see that variable `y` is not accessible outside the method because it is valid only in the method. 

Another possible scenario is that if you use the same variable names outside and inside the method, Python chooses the value of that varaible inside the method (override). For new programmer, we do not encourage this unless you have a clear code map how the data flow takes place. 

### Exercise 14 (code study)

In the code below, if you run it, the result is different from what we expect. We want to calculate $y=f(x)=3x^2 + 2x + 1$ and we want to calculate each product first and then sum it together to get the results. But somehow Python says it is wrong.

Can you fix it?

In [10]:
a = 3
b = 2
c = 1

def quad_eq2(x):   
    
    # get the products (c, bx and ax^2)
    a = c
    b = b * x
    c = a * x**2
    
    # then sum them together
    y = a + b + c
    
    return y

In [11]:
quad_eq2(1)

UnboundLocalError: cannot access local variable 'c' where it is not associated with a value

## Case study: LU decomposition (for MAT 460)

Lets solve a system of linear equations Ax=b, using the LU decomposition.

In the code below, we build two methods. The *main* method which we use to test the LU decomposition method, and the LU decomposition method itself. 


In [39]:
''' 
MAT 460, HW 1ab, Author, Date

Solve Ax=b using LU decomposition
(1) A=LU, (2) solve Ly=b, (3) solve Ux=y

Testcase: Ax=b has solution x = [1,2,3]^T 
for
L = np.array([[1,0,0],[-2,1,0],[4,5,1]])
U = np.array([[2,-1,6],[0,3,9],[0,0,-2]])
b = np.array([18,-3,231])
'''

import numpy as np 
import scipy.linalg as la     # what is this?

def main(): 

    # (2) solve Ly=b
    L = np.array([[1,0,0],[-2,1,0],[4,5,1]])
    b = np.array([18,-3,231])
    y = my_forward(L,b)
    # compare with python linear algebra library solver
    print(y,"=?=",la.solve(L,b))
    
    # example from hwset 1 
    U = np.array([[2,-1,6],[0,3,9],[0,0,-2]])
    A = np.dot(L,U)
    print(A)
    
    x = la.solve(A,b)
    print(x)
    
    
# function definitions start  
def my_forward(L,b):
    ''' solve lower triangular system: Ly = b
    for k = 0...n-1         
       b_k = y_k
       for j = 0...k 
          y_k = y_k - l_kj y_j
    '''
    n = L.shape[0]
    y = np.zeros(n)        
    for k in range(n):         
        y[k] = b[k]
        for j in range(k):      
            y[k] = y[k] - L[k,j]*y[j]             
    return y


if __name__ == "__main__":
    main()     

[18. 33. -6.] =?= [18. 33. -6.]
[[ 2 -1  6]
 [-4  5 -3]
 [ 8 11 67]]
[1. 2. 3.]


Develop the algorithm for the backward solver. Over which index pairs do we have to loop? Write the pseudo-code for this function.
Change the following piece of code so that these 2 for-loops give the number pairs (k,j) = (2,2), (1,1), (1,2), (0,0), (0,1), (0,2).

In [40]:
n = 3
for k in range(n,-1,1):
    for j in range(k+1,n):
        print(k,j)

### Exercise 15 (backward decomposition)

```
# TODO
#def backward(U,y):
#    return x

# make hw easier, we allow using python to do the A=LU
#def myLU(A):
#    return L,U
```

It remains to fill in the two methods so that we complete the diagonalization. Please refer to your homework assignment. 

## PEPs and more in-depth Python tutorials

> The [Zen of Python](https://www.python.org/dev/peps/pep-0020/) and [Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#other-recommendations)

> [https://docs.python-guide.org/](https://docs.python-guide.org/)

> [https://docs.python-guide.org/intro/learning/](https://docs.python-guide.org/intro/learning/)

> [http://www.davekuhlman.org/python_book_01.html](http://www.davekuhlman.org/python_book_01.html)

<font color='purple'> What are PEPs? Can you give 3 examples for good coding style.  
Andrea liked Kuhlman's book. It has 3 parts: Beginning, Advanced, and Exercises with Solutions (''for those who feel a need for less explanation and more practical exercises'').</font>